name: Process Test Results

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

permissions: {}

jobs:
  process-test-results:
    name: Process Test Results
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'skipped'

    permissions:
      checks: write

      # needed unless run with comment_mode: off
      pull-requests: write

      # required by download step to access artifacts API
      actions: read

    steps:
      - name: Dump workflow_run
        env:
          WORKFLOW_CONTEXT: ${{ toJson(github.event.workflow_run) }}
        run: echo "$WORKFLOW_CONTEXT"
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          github-token: ${{ github.token }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          action_fail_on_inconclusive: true
          check_name: "Test Results (${{ github.event.workflow_run.event || github.event_name }})"
          time_unit: milliseconds
          commit: ${{ github.event.workflow_run.head_sha }}
          event_file: artifacts/Event File/event.json
          event_name: ${{ github.event.workflow_run.event }}
          files: "artifacts/Test Results/*.json"
      - name: Create context file
        run: |
            printf '{ 
              "event": "${{github.event.workflow_run.event}}"
            }' >> artifacts/context.json
      - name: Upload Event File
        uses: actions/upload-artifact@v4
        with:
          name: Event File
          path: artifacts/Event File/event.json
      - name: Upload Context File
        uses: actions/upload-artifact@v4
        with:
          name: Context File
          path: artifacts/context.json
