# Workflow to push the change to deploy the change to players
# on push to master much quicker without waiting for cron jobs.
name: Deploy
on:
  workflow_run:
    workflows: ["Process Test Results"]
    types:
      - completed
jobs:
  get_context:
    runs-on: ubuntu-latest
    if: |
      github.repository == 'saurtron/Beyond-All-Reason' &&
      github.event.workflow_run.conclusion == 'success'
    outputs:
      event: ${{ fromJson(steps.context.outputs.data).event }}
      branch: ${{ fromJson(steps.context.outputs.data).branch }}
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          github-token: ${{ github.token }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: Get context json
        id: context
        run: echo "data=$(jq -c . < 'artifacts/Context File/context.json')" >> $GITHUB_OUTPUT
  deploy:
    needs: [get_context]
    runs-on: ubuntu-latest
    if: |
      needs.get_context.outputs.event == 'push' &&
      needs.get_context.outputs.branch == 'master'
    permissions:
      id-token: write
    steps:
      - name: Trigger rebuild
        run: |
          echo "$SSH_KEY" > id.key
          chmod og-rwx id.key
          ssh -i id.key -o StrictHostKeyChecking=no debian@repos.beyondallreason.dev byar
        env:
          SSH_KEY: ${{ secrets.SSH_REPOS_DEPLOY_KEY }}
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/640511349987/locations/global/workloadIdentityPools/github-actions/providers/github
          service_account: github-actions@bar-rapid-syncer-176212.iam.gserviceaccount.com
          token_format: id_token
          id_token_audience: cdnupdater
          id_token_include_email: true
      - name: Sync files to CDN
        run: |
          curl --fail -H "Authorization: Bearer ${{ steps.auth.outputs.id_token }}" \
            -X POST -d '["byar"]' https://rapidsyncer-ssd-7xiouooxaa-ey.a.run.app/sync
      - name: Update CDN pointer
        run: |
          curl --fail -H "Authorization: Bearer ${{ steps.auth.outputs.id_token }}" \
            -X GET https://bunny-update-edge-rule-7xiouooxaa-ew.a.run.app/update-edge-rule.sh
