name: Run Tests

on:
#  pull_request
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'master'

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Tests
        run: docker compose -f tools/headless_testing/docker-compose.yml up
        timeout-minutes: 30

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          action_fail_on_inconclusive: true
          check_name: "Test Results"
          time_unit: milliseconds
          commit: ${{ github.head_sha }}
          event_file: ${{ github.event_path }}
          event_name: ${{ github.event_name }}
          files: "tools/headless_testing/testlog/results.json"
