name: Run Tests

on:
#  pull_request
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'master'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Tests
        run: docker compose -f tools/headless_testing/docker-compose.yml up
        timeout-minutes: 30

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: tools/headless_testing/testlog/results.json

  test-results:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          action_fail: true
          action_fail_on_inconclusive: true
          check_name: "Test Results"
          time_unit: milliseconds
          commit: ${{ github.head_sha }}
          event_file: ${{ github.event_path }}
          event_name: ${{ github.event_name }}
          files: "artifacts/Test Results/*.json"

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test-results
    if: |
      github.repository == 'beyond-all-reason/Beyond-All-Reason' &&
      github.event_name == 'push' &&
      github.ref == 'refs/heads/master'
    permissions:
      id-token: write
    steps:
      - name: Trigger rebuild
        run: |
          echo "$SSH_KEY" > id.key
          chmod og-rwx id.key
          ssh -i id.key -o StrictHostKeyChecking=no debian@repos.beyondallreason.dev byar
        env:
          SSH_KEY: ${{ secrets.SSH_REPOS_DEPLOY_KEY }}

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/640511349987/locations/global/workloadIdentityPools/github-actions/providers/github
          service_account: github-actions@bar-rapid-syncer-176212.iam.gserviceaccount.com
          token_format: id_token
          id_token_audience: cdnupdater
          id_token_include_email: true

      - name: Sync files to CDN
        run: |
          curl --fail -H "Authorization: Bearer ${{ steps.auth.outputs.id_token }}" \
            -X POST -d '["byar"]' https://rapidsyncer-ssd-7xiouooxaa-ey.a.run.app/sync

      - name: Update CDN pointer
        run: |
          curl --fail -H "Authorization: Bearer ${{ steps.auth.outputs.id_token }}" \
            -X GET https://bunny-update-edge-rule-7xiouooxaa-ew.a.run.app/update-edge-rule.sh
